### ISSUE TITLE
Upgrade 3.3.4 to 3.3.5 seems to be broken

### ISSUE THREAD

**Issue by kruthoff** [nextcloud/recognize#628]
### Which version of recognize are you using?

3.3.5

### Enabled Modes

Face recognition

### TensorFlow mode

WASM mode

### Which Nextcloud version do you have installed?

25.0.2

### Which Operating system do you have installed?

Debian 11

### Which Docker container are you using to run Nextcloud? (if applicable)

-

### How much RAM does your server have?

8GiB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

Upgrade to version 3.3.5 fails. Face recognition does not work anymore. It was working with version 3.3.4.
It looks like the `node` binary was removed during the upgrade.
```
root@delta3:/var/www/html/nextcloud# ls -la /var/www/html/nextcloud/apps/recognize/bin/
total 8
drwxr-xr-x  2 www-data www-data 4096 Jan 14 11:16 .
drwxr-xr-x 12 www-data www-data 4096 Jan 14 11:16 ..
root@delta3:/var/www/html/nextcloud#
```
GUI Status:

- The machine learning models still need to be downloaded.
- Could not execute the Node.js binary. You may need to set the path to a working binary manually. 

### Expected Behavior

A working recognize app, as it was before with 3.3.4.

### To Reproduce

Disable and enable the recognize app did not help.
Remove and add/enable the app did not help.

### Debug log

Nextcloud log:

```
{"reqId":"qc7eNILh2wnDko4CmA8W","level":3,"time":"2023-01-14T11:06:39+01:00","remoteAddr":"192.168.1.70","user":"admin","app":"PHP","method":"GET","url":"/settings/apps/update/recognize","message":"chmod(): No such file or directory at /var/www/html/nextcloud/apps/recognize/lib/Migration/InstallDeps.php#145","userAgent":"Mozilla/5.0 (X11; Linux armv7l; rv:102.0) Gecko/20100101 Firefox/102.0","version":"25.0.2.3","exception":{"Exception":"Error","Message":"chmod(): No such file or directory at /var/www/html/nextcloud/apps/recognize/lib/Migration/InstallDeps.php#145","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/html/nextcloud/apps/recognize/lib/Migration/InstallDeps.php","line":145,"function":"chmod"},{"file":"/var/www/html/nextcloud/apps/recognize/lib/Migration/InstallDeps.php","line":78,"function":"testBinary","class":"OCA\\Recognize\\Migration\\InstallDeps","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Repair.php","line":127,"function":"run","class":"OCA\\Recognize\\Migration\\InstallDeps","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/legacy/OC_App.php","line":1064,"function":"run","class":"OC\\Repair","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/legacy/OC_App.php","line":1006,"function":"executeRepairSteps","class":"OC_App","type":"::"},{"file":"/var/www/html/nextcloud/lib/private/Installer.php","line":200,"function":"updateApp","class":"OC_App","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/nextcloud/apps/settings/lib/Controller/AppSettingsController.php","line":535,"function":"updateAppstoreApp","class":"OC\\Installer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"updateApp","class":"OCA\\Settings\\Controller\\AppSettingsController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/nextcloud/lib/base.php","line":1047,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}
{"reqId":"qc7eNILh2wnDko4CmA8W","level":3,"time":"2023-01-14T11:06:39+01:00","remoteAddr":"192.168.1.70","user":"admin","app":"recognize","method":"GET","url":"/settings/apps/update/recognize","message":"Failed to install Tensorflow.js: sh: 1: /var/www/html/nextcloud/apps/recognize/bin/node: not found","userAgent":"Mozilla/5.0 (X11; Linux armv7l; rv:102.0) Gecko/20100101 Firefox/102.0","version":"25.0.2.3","data":{"app":"recognize"}}
{"reqId":"qc7eNILh2wnDko4CmA8W","level":3,"time":"2023-01-14T11:06:39+01:00","remoteAddr":"192.168.1.70","user":"admin","app":"no app in context","method":"GET","url":"/settings/apps/update/recognize","message":"Exception while executing repair step Install dependencies","userAgent":"Mozilla/5.0 (X11; Linux armv7l; rv:102.0) Gecko/20100101 Firefox/102.0","version":"25.0.2.3","exception":{"Exception":"Exception","Message":"Failed to install Tensorflow.js: sh: 1: /var/www/html/nextcloud/apps/recognize/bin/node: not found","Code":0,"Trace":[{"file":"/var/www/html/nextcloud/apps/recognize/lib/Migration/InstallDeps.php","line":90,"function":"runTfjsInstall","class":"OCA\\Recognize\\Migration\\InstallDeps","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Repair.php","line":127,"function":"run","class":"OCA\\Recognize\\Migration\\InstallDeps","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/legacy/OC_App.php","line":1064,"function":"run","class":"OC\\Repair","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/legacy/OC_App.php","line":1006,"function":"executeRepairSteps","class":"OC_App","type":"::"},{"file":"/var/www/html/nextcloud/lib/private/Installer.php","line":200,"function":"updateApp","class":"OC_App","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/nextcloud/apps/settings/lib/Controller/AppSettingsController.php","line":535,"function":"updateAppstoreApp","class":"OC\\Installer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"updateApp","class":"OCA\\Settings\\Controller\\AppSettingsController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/nextcloud/lib/base.php","line":1047,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/nextcloud/apps/recognize/lib/Migration/InstallDeps.php","Line":173,"message":"Exception while executing repair step Install dependencies","exception":{},"CustomMessage":"Exception while executing repair step Install dependencies"}}
```

**Comment by thtwice** [comment]
Same here.
On RaspberrypiOS.
4GB of RAM.
Nextcloud installed via docker.

**Comment by nonofr91** [comment]
I also have problem after update:

Erreur | PHP | Error: chmod(): No such file or directory at /config/www/nextcloud/apps/recognize/lib/Migration/InstallDeps.php#145

Erreur | no app in context | Exception: Failed to install Tensorflow.js: sh: /config/www/nextcloud/apps/recognize/bin/node: not found

**Comment by rauschgiftengel** [comment]
Same, 
tried to downgrade and moved the missing files in place, but installer failed again.

so i downgraded to previous version an everyting is fine for now.
steps:

deactivate recognize app
removed the folder recognize under the custom apps
downloaded previous .tar from app-store
extract it to the custom apps folder
fixed permission to www-data
finaly activated app again 

UPDATE,

after a working previous version, i tried an occ repair, wich updated the recognize app again, but now it is working with the latest update :D

**Comment by Edsonytic** [comment]
3.3.5 is also broken doing a fresh install

**Comment by liftandpray** [comment]
Got a workaround to get 3.3.5 working:

1.	Deactivated and removed app with gui
2.	Downloaded 3.3.4 .tar 
3.	Extracted 3.3.4 into ~/nextcloud/apps/ folder
4.	Adjusted permissions to www-data
5.	Enabled app in gui
6.	Confirmed everything was back to normal
7.	Deactivated app in gui
8.	Copied the “x64.tar.gz” and “node” file’s from  ~/nextcloud/apps/recognize/bin/ folder & moved to temporary folder
9.	Upgraded recognize via the GUI
10.	Copied the “x64.tar.gz” and “node” file’s back to ~/nextcloud/apps/recognize/bin/  folder
11.	Enabled recognize app via the GUI
12.	Re-downloaded the learning models via command line
13.	Working as expected now!

**Comment by ernolf** [comment]
For Debian and Ubuntu:

Test your nodejs version:

    node -v

if node version < 14.17

- Install Node like described here: [deb installation instructions](https://github.com/nodesource/distributions/blob/master/README.md#debinstall)

You don't have to visit that link, here are the steps you need:
Since we  need node 14 (newer versions may use newer libc and can be incompatible with your ubuntu/debian version) run these commands:

    curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash - &&\
    sudo apt-get install -y nodejs

now

    node -v

should answer `v14.21.2` which is > 14.17, thus the one we need

(If you want, you may run

    sudo apt-get -y autoremove

to remove the now obsolete old node packages)

Verify the path of the node binary:

    which node

(normaly `/usr/bin/node`)
and enter that path in the field provided in the admin view.

Then run occ to download machine learning models:

    ./occ  recognize:download-models

Ready.

**Comment by ernolf** [comment]
For Debian and Ubuntu:
(No guarantee but this worked for me)

Test your nodejs version:

    node -v

if node version < 14.17

- Install Node like described here: [deb installation instructions](https://github.com/nodesource/distributions/blob/master/README.md#debinstall)

You don't need to open that link, here are the necessary steps taken from there:

Since we  need node 14 (newer versions may use newer libc and can be incompatible with your ubuntu/debian version) run these commands:

    curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash - &&\
    sudo apt-get install -y nodejs

now

    node -v

should answer `v14.21.2` which is > 14.17, thus the one we need

(If you want, you may run
    sudo apt-get -y autoremove
to remove the now obsolete old node packages)

Verify the path of the node binary:

    which node

(normaly `/usr/bin/node`)
and enter that path in the field provided in the admin view.

Now run occ to download machine learning models:

    ./occ  recognize:download-models

I hope this works for you.

**Comment by dzacball** [comment]
Same here. Node binary is gone after upgrade.

**Comment by adrianog91** [comment]
same here

**Comment by JeCheeseSmith** [comment]
also same here

**Comment by archnemeziz** [comment]
All npm binaries including node are gone as described by others. 
Attempted to do npm ci in recognize directory but it fails to download tensorflow and fails the install.
Manually setting npm binary directory does work.

**Comment by archnemeziz** [comment]
> 

Update on this - just node binary was gone. When I tried to do npm ci it deleted all the modules.
After downgrading to 3.3.4 tensorflow wasn't working but I was able to successfully do npm ci and it works now.

So it seems that just node binary is missing from the update.

**Comment by ralfi** [comment]
as @ernolf wrote works for me, appended by manual install of libtensorflow how that described at the wiki.

**Comment by marcelklehr** [comment]
Should be fixed with v3.3.6

**Comment by methyphobia** [comment]
> Should be fixed with v3.3.6

Confirmed. Error is gone in v.3.3.6

**Comment by MayeulC** [comment]
I just hit that issue when I upgraded to 3.3.6 a few minutes ago. Face recognition used to work; I had to re-download the models, but the node binary is gone from `recognize/bin`

I do have a system-wide node install, but this is Debian, so the version is v6.17.1

**Comment by ralfi** [comment]
You should remove 3.3.5 and then install 3.3.6. That works here.

**Comment by MayeulC** [comment]
@ralfi I think triggering the dependency install step manually should solve the issue, but I am not sure if that's easy to do.

Question: if I remove recognize, will I lose all my clusters? I spent a lot of time cleaning the thousands of faces I have.

**Comment by ralfi** [comment]
Not sure but dont think so

**Comment by MayeulC** [comment]
I just followed the script manually to install node, which works, but I'd have to do the same for tensorflow and other dependencies... I'd really appreciate a way to re-run that part automatically.
```
wget https://nodejs.org/dist/v14.18.2/node-v14.18.2-linux-x64.tar.gz
tar -xzf node-v14.18.2-linux-x64.tar.gz node-v14.18.2-linux-x64/bin/node
mv node-v14.18.2-linux-x64/bin/node /var/www/nextcloud/apps/recognize/bin
chown nextcloud:nextcloud /var/www/nextcloud/apps/recognize/bin
```

**Comment by nyok92** [comment]
Hi , I uninstalled Recognize app, then installed it back (last version), but still have an error :

{"reqId":"uvFahRJ9LNx1T9HlZfAn","level":3,"time":"2023-01-18T12:04:34+00:00","remoteAddr":"10.0.0.2","user":"admin","app":"PHP","method":"POST","url":"/settings/apps/enable","message":"chmod(): No such file or directory at /var/www/html/custom_apps/recognize/lib/Migration/InstallDeps.php#146","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36","version":"25.0.3.2","exception":{"Exception":"Error","Message":"chmod(): No such file or directory at /var/www/html/custom_apps/recognize/lib/Migration/InstallDeps.php#146","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"chmod(): No such file or directory","/var/www/html/custom_apps/recognize/lib/Migration/InstallDeps.php",146]},{"file":"/var/www/html/custom_apps/recognize/lib/Migration/InstallDeps.php","line":146,"function":"chmod","args":["/var/www/html/custom_apps/recognize/bin/node",493]},{"file":"/var/www/html/custom_apps/recognize/lib/Migration/InstallDeps.php","line":78,"function":"testBinary","class":"OCA\\Recognize\\Migration\\InstallDeps","type":"->","args":["/var/www/html/custom_apps/recognize/bin/node"]},{"file":"/var/www/html/lib/private/Repair.php","line":127,"function":"run","class":"OCA\\Recognize\\Migration\\InstallDeps","type":"->","args":[{"__class__":"OC\\Repair"}]},{"file":"/var/www/html/lib/private/legacy/OC_App.php","line":1064,"function":"run","class":"OC\\Repair","type":"->","args":[]},{"file":"/var/www/html/lib/private/Installer.php","line":156,"function":"executeRepairSteps","class":"OC_App","type":"::","args":["recognize",["OCA\\Recognize\\Migration\\InstallDeps"]]},{"file":"/var/www/html/apps/settings/lib/Controller/AppSettingsController.php","line":451,"function":"installApp","class":"OC\\Installer","type":"->","args":["recognize"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"enableApps","class":"OCA\\Settings\\Controller\\AppSettingsController","type":"->","args":[["recognize"],[]]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\AppSettingsController"},"enableApps"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\AppSettingsController"},"enableApps"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Settings\\Controller\\AppSettingsController","enableApps",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},["settings.AppSettings.enableApps"]]},{"file":"/var/www/html/lib/base.php","line":1047,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/settings/apps/enable"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}

**Comment by ralfi** [comment]
Yes, also here. Same with 25.0.3.
Seems to me (not really based on dev knowledge ...) InstallDeps.php must be changed.

**Comment by kruthoff** [comment]
@nyok92 @ralfi I suggest that you create a new issue for your finding.
